---
- name: Create a OSP User
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:

   - name: Create OSP User
     os_user_facts:
        name: test-admin
        auth:
          auth_url: https://192.168.200.10:13000/v2.1
   - debug:
     var: openstack_users
