---
- name: Create Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
        
   - name: Create a new instance and attaches to a network and passes metadata to the instance
     os_server:
        state: present
        auth:
          auth_url: https://192.168.200.10:13000/v3
          domain_name: Default
          password: r3dh4t!
          project_name: test-drive
          username: td-admin
        verify: no
        name: vmtest1
        image: 	RHEL-7
        key_name: test-drive-key
        timeout: 200
        flavor: m1.tiny
        nics:
         - net-name: private
        meta:
           hostname: test1
