---
- name: Create a OSP User
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:

   - name: Create OSP User
     os_user:
        state: present
        name: test
        password: secret
        email: test@example.com
        domain: default
        default_project: test-drive
        auth:
          auth_url: https://192.168.200.10:13000/v3
          username: td-admin
          password: r3dh4t!
        verify: no
   - debug:
     var: openstack_user
